const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{janela: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Solid: 0},
	{suporte: 0},
	{Flash: 0},
	{bau: 0},
	{Sprite3: 0},
	{Platform: 0},
	{caixa: 0},
	{Sprite4: 0},
	{porta: 0},
	{CHAVE: 0},
	{BOMBA: 0},
	{ScrollTo: 0},
	{JOGADOR: 0},
	{SENSOR_solido: 0},
	{Keyboard: 0},
	{DIRACAO: 0},
	{porcopatrulheiro: 0},
	{SERSORPATRULHEIRO: 0},
	{SERSORPATRULHEIRO2: 0},
	{portocanhao: 0},
	{CANHAO: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{BALA: 0},
	{Sprite5: 0},
	{SERSORCANHAO: 0},
	{VIDA_HUD: 0},
	{ITENS_HUD: 0},
	{BLACK_BLACK: 0},
	{CABECADIALOGO: 0},
	{SpriteFont: 0},
	{Tilemap2: 0},
	{BLOCOS: 0},
	{Sprite6: 0},
	{CHEFAO: 0},
	{Audio: 0},
	{Tilemap3: 0},
	{JANELAS: 0},
	{SUPORTES: 0},
	{CAIXAS: 0},
	{PORTAS: 0},
	{chave2: 0},
	{BOMBA2: 0},
	{JOGADO: 0},
	{SERSOR_SOLIDO: 0},
	{INIMIGO1: 0},
	{DIRECAO: 0},
	{inimigos1: 0},
	{SENSOR_INIMIGO1_D: 0},
	{SENSOR_INIMIGO1_E: 0},
	{INIMIGOS_02: 0},
	{ARMA_2: 0},
	{DANO_2: 0},
	{SENSOR_BALA: 0},
	{MALA_2: 0},
	{SENSOR_INIMIGO1_D2: 0},
	{DIRECAO2: 0},
	{INIMIGO_3: 0},
	{SENSOR_MOVIMENTO2D: 0},
	{SENSOR_MOVIMENTO3E: 0},
	{solido: 0},
	{CHAVES2: 0},
	{REI2: 0},
	{Sprite7: 0},
	{Tilemap4: 0},
	{LOGO_JOGO: 0},
	{COR__: 0},
	{Text: 0},
	{Text2: 0},
	{Button2: 0},
	{FUNDO_INICIO: 0},
	{TRANSPARENTE: 0},
	{Button: 0},
	{VIDAS: 0},
	{VIDA: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	janela: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	suporte: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	JOGADOR: class extends self.ISpriteInstance {},
	SENSOR_solido: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	porcopatrulheiro: class extends self.ISpriteInstance {},
	SERSORPATRULHEIRO: class extends self.ISpriteInstance {},
	SERSORPATRULHEIRO2: class extends self.ISpriteInstance {},
	portocanhao: class extends self.ISpriteInstance {},
	CANHAO: class extends self.ISpriteInstance {},
	BALA: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	SERSORCANHAO: class extends self.ISpriteInstance {},
	VIDA_HUD: class extends self.ISpriteInstance {},
	ITENS_HUD: class extends self.ISpriteInstance {},
	BLACK_BLACK: class extends self.ISpriteInstance {},
	CABECADIALOGO: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	CHAVE: class extends self.ISpriteInstance {},
	BOMBA: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	BLOCOS: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	CHEFAO: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	JANELAS: class extends self.ISpriteInstance {},
	SUPORTES: class extends self.ISpriteInstance {},
	CAIXAS: class extends self.ISpriteInstance {},
	PORTAS: class extends self.ISpriteInstance {},
	JOGADO: class extends self.ISpriteInstance {},
	SERSOR_SOLIDO: class extends self.ISpriteInstance {},
	INIMIGO1: class extends self.ISpriteInstance {},
	inimigos1: class extends self.ISpriteInstance {},
	SENSOR_INIMIGO1_D: class extends self.ISpriteInstance {},
	SENSOR_INIMIGO1_E: class extends self.ISpriteInstance {},
	INIMIGOS_02: class extends self.ISpriteInstance {},
	ARMA_2: class extends self.ISpriteInstance {},
	DANO_2: class extends self.ISpriteInstance {},
	SENSOR_BALA: class extends self.ISpriteInstance {},
	MALA_2: class extends self.ISpriteInstance {},
	SENSOR_INIMIGO1_D2: class extends self.ISpriteInstance {},
	INIMIGO_3: class extends self.ISpriteInstance {},
	SENSOR_MOVIMENTO2D: class extends self.ISpriteInstance {},
	SENSOR_MOVIMENTO3E: class extends self.ISpriteInstance {},
	solido: class extends self.ISpriteInstance {},
	CHAVES2: class extends self.ISpriteInstance {},
	BOMBA2: class extends self.ISpriteInstance {},
	REI2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Tilemap4: class extends self.ITilemapInstance {},
	LOGO_JOGO: class extends self.ISpriteInstance {},
	COR__: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Button2: class extends self.IButtonInstance {},
	FUNDO_INICIO: class extends self.ISpriteInstance {},
	TRANSPARENTE: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {}
}